---

- hosts: servers14
  become: true
  tasks:

  - name: install apache2 package and add php support for Ubuntu
    apt:
      name: 
        - apache2 
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install httpd package and add php support for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"