---

- hosts: servers14
  become: true
  tasks:

  - name: install apache2 package and add php support
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes