---

- hosts: servers14
  become: true
  tasks:

  - name: remove apache2 package and remove php support
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes