- name: install apache2 package and add php support for Ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name: 
      - apache2 
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: install httpd package and add php support for CentOS
  tags: apache,httpd,centos
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: start httpd (CentOS)
  tags: httpd,apache,centos
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regex: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "CentOS"
  register: nitishchopra

- name: restart httpd service (CentOS)
  tags: apache,httpd,centos
  service:
    name: httpd
    state: restarted
  when: nitishchopra.changed