- name: install unzip
  tags: workstations
  package:
    name: unzip

- name: install terraform
  tags: workstations
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.0.1/terraform_1.0.1_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root